[package]
name = "wei-docker-linux"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 'z'

[dependencies]
wei-log = "0.2.10"
tokio = { version = "1", features = ["full"] }
serde_json = "1"
percent-encoding = "2.3.1"
reqwest = "0.11"
base64 = "0.13"